# Site settings
title:                  His Royal Redness
email:                  hisroyalredness@gmail.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:                ""
url:                    http://hisroyalredness.com
title_description:      My little piece of web turf.
#title_image:           "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm" 
post_limit:             5


# Social usernames/URLs
twitter_username:       HisRoyalRedness
github_username:        HisRoyalRedness
#linkedin_link:         http://nz.linkedin.com/in/kfletcher/
google_plus_link:       https://plus.google.com/u/0/117142223002091818996/
#stackoverflow_link:    http://stackoverflow.com/users/544196/his-royal-redness/
#google_analytics:      UA-76004360-1
#disqus_account:        fletcherorgnz
github_repository:      https://github.com/HisRoyalRedness/HisRoyalRedness.github.io
addthis_id:             ra-5703571c5aab0aaf


# Build settings
markdown:               kramdown
highlighting:           rouge
