# Site settings
title:                  His Royal Redness
email:                  hisroyalredness@gmail.com
description: >
  This is the personal website of Keith Fletcher, aka HisRoyalRedness.
  I use it as my scribble pad, and it consists primariy of notes that 
  I keep to remind myself later when memory fails. Occasionally, I'll
  post the odd random thought or opinion.
baseurl:                ""
url:                    http://hisroyalredness.com
title_description:      My little piece of web turf.
title_image:           http://hisroyalredness.com/image/hrr_square.png
post_limit:             5


# Social usernames/URLs
twitter_username:       HisRoyalRedness
github_username:        HisRoyalRedness
linkedin_username:      kfletcher
google_plus_link:       https://plus.google.com/u/0/117142223002091818996/
#stackoverflow_link:    http://stackoverflow.com/users/544196/his-royal-redness/
#google_analytics:      UA-76004360-1
#disqus_account:        fletcherorgnz
github_repository:      https://github.com/HisRoyalRedness/HisRoyalRedness.github.io
addthis_id:             ra-5703571c5aab0aaf

# GPG
fingerprint:            5D71 582C DCBF 8105 BD41  94E9 0F0D 6084 0F97 A170
long_id:                0F0D60840F97A170
short_id:               0F97A170

# Build settings
markdown:               kramdown

highlighting:           rouge
